site_name: scGen Documentation
site_description: 'Documentation for ScGen, the generative model to predict single-cell perturbation response across cell types, studies and species.'
docs_dir: docs/sources
repo_url: http://github.com/theislab/scgen
theme:
  name: null
  custom_dir: theme
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: false
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Models:
    - VAE: 'models/vae.md'
    - utils: 'models/utils.md'
    - read_load: 'read_load.md'
    - plotting: 'plotting.md'
