site_name: scGen Documentation
docs_dir: 'docs/sources/'
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - models:
    - About: 'models/index.md'
    - VAE: 'models/vae.md'
    - utils: 'models/utils.md'
  - read_load: 'read_load.md'
  - plotting: 'plotting.md'
theme: readthedocs
repo_url: http://github.com/theislab/scgen
site_description: 'Documentation for ScGen, the generative model to predict single-cell perturbation response across cell types, studies and species.'